### ISSUE TITLE
Reentrancy Protection

### ISSUE THREAD

**Issue by vking45** [PsyCodeLabs/noteFi-contracts#1]
Fallback and Reentrancy Protection needs to be added in the smart contracts. For the fallback, just simply revert the transaction and any standard reentrancy guard can be used.

**Comment by kamuik16** [comment]
> Fallback and Reentrancy Protection needs to be added in the smart contracts. For the fallback, just simply revert the transaction and any standard reentrancy guard can be used.

We'll Openzeppelin's Reentrancy Guard.
