### ISSUE TITLE
Use SafeMath

### ISSUE THREAD

**Issue by vking45** [PsyCodeLabs/noteFi-contracts#2]
This issue is open for discussion and debate, whether there exists a need to use SafeMath library or not for the mathematical operations taking place inside the `Call.sol` and `Put.sol` contracts ?

**Comment by kamuikatsurgi** [comment]
> This issue is open for discussion and debate, whether there exists a need to use SafeMath library or not for the mathematical operations taking place inside the `Call.sol` and `Put.sol` contracts ?

Yeah, we'll need to use Safemath for that.

**Comment by kamuikatsurgi** [comment]
Openzeppelin has this, I guess.

**Comment by vking45** [comment]
> Openzeppelin has this, I guess.

Yes it does, here's the link to that - https://docs.openzeppelin.com/contracts/2.x/api/math
Marking this issue from question -> enhancement + priority

**Comment by vking45** [comment]
After a thorough review, I believe currently there is no need for using SafeMath as there are not any computations of sort in the contract logic, we might need to implement it in the future.
