### ISSUE TITLE
Modifiers add bytecode size

### ISSUE THREAD

**Issue by pegahcarter** [PsyCodeLabs/noteFi-contracts#20]
I suggest having the modifiers call private methods to check state, rather than checking state within the modifier.  Each time a modifier decorates a function, all of its' internal code is prepended to the bytecode.  So, if you have a modifier which has a string in it directly, that string bytecode will be appended to all decorated functions.  By having a private function within the modifier which contains the string, only a pointer to the private function is used vs. the string from the bytecode.

**Comment by vking45** [comment]
Thank you for the suggestion, will make sure to get this change implemented.
