### ISSUE TITLE
Implement Upgradeable Proxy

### ISSUE THREAD

**Issue by vking45** [PsyCodeLabs/noteFi-contracts#34]
The `Factory` contract needs to be implemented in an upgradeable manner, this will help fix bugs and introduce upgrades in future.

PS : suggested by @kamuikatsurgi

**Comment by kamuikatsurgi** [comment]
There are multiple upgradeability methods. This [video](https://youtu.be/e5lWvt1rIm0?si=8NtL3uP3wouNjWG_) is a nice overview of some of the majorly used methods.

**Comment by mystical-prog** [comment]
I guess using UUPS seems easier and would serve the need for atleast testnet.

**Comment by vking45** [comment]
After a thorough consideration, I believe Upgradeability is redundant in V1, can be implemented in V2 when there will be much advance functionality.
